name: LifeLink
version: ${project.version}
main: com.spacelampsix.LifeLink.LifeLink
api-version: 1.13
authors: [KyleEvangelisto]
description: If one player dies, all of them do.
website: kyleevangelisto.com
